const mongoose = require('mongoose');

const feeReceiptSchema = new mongoose.Schema(
  {
    school: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: 'School', 
      required: true, 
      index: true 
    },
    student: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: 'StudentAdmission', 
      required: true,
      index: true
    },
    payment: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: 'FeePayment', 
      required: true
    },
    
    // Receipt Details
    receiptNumber: { 
      type: String, 
      required: true, 
      unique: true,
      trim: true 
    },
    date: { 
      type: Date, 
      required: true,
      default: Date.now
    },
    
    // Amount Details
    amount: { 
      type: Number, 
      required: true,
      min: 0
    },
    
    // Status
    status: { 
      type: String, 
      enum: ['Active', 'Cancelled'],
      default: 'Active'
    },
    
    // Generated By
    generatedBy: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: 'School',
      default: null
    },
  },
  { 
    timestamps: true 
  }
);

// Indexes
feeReceiptSchema.index({ school: 1, student: 1 });
feeReceiptSchema.index({ school: 1, date: -1 });

// Generate receipt number before saving
feeReceiptSchema.pre('save', async function(next) {
  if (!this.receiptNumber) {
    const count = await mongoose.model('FeeReceipt').countDocuments({ school: this.school });
    const year = new Date().getFullYear().toString().slice(-2);
    this.receiptNumber = `RCP${year}${String(count + 1).padStart(6, '0')}`;
  }
  next();
});

module.exports = mongoose.model('FeeReceipt', feeReceiptSchema);
